"""Generates the 20 milestone "boss" masks (levels 50,100,...,1000) and writes
them to lib/data/boss_shapes.dart.

Each is a distinct, intricate, SOLID parametric silhouette (star / gear / flower
/ gem / sun). Size and complexity grow with the milestone so level 1000 is the
biggest and hardest. Solid shapes keep the carve dense (long arrows)."""
import math
import os


def _grid(size):
    return [["."] * size for _ in range(size)]


def _emit(g):
    return ["".join(r) for r in g]


def star(size, points, inner=0.52, sharp=1.4):
    g = _grid(size)
    c = (size - 1) / 2
    R = c * 0.97
    for y in range(size):
        for x in range(size):
            dx, dy = x - c, y - c
            r = math.hypot(dx, dy)
            th = math.atan2(dy, dx)
            f = (0.5 + 0.5 * math.cos(points * th)) ** sharp
            if r <= R * (inner + (1 - inner) * f):
                g[y][x] = "#"
    return g


def gear(size, teeth, body=0.68, hole=0.16):
    g = _grid(size)
    c = (size - 1) / 2
    Rt = c * 0.97
    Rb = c * body
    for y in range(size):
        for x in range(size):
            dx, dy = x - c, y - c
            r = math.hypot(dx, dy)
            th = math.atan2(dy, dx)
            R = Rt if math.cos(teeth * th) > 0.1 else Rb
            if hole * c <= r <= R:
                g[y][x] = "#"
    return g


def flower(size, petals):
    g = _grid(size)
    c = (size - 1) / 2
    for y in range(size):
        for x in range(size):
            dx, dy = x - c, y - c
            r = math.hypot(dx, dy)
            th = math.atan2(dy, dx)
            rb = c * (0.5 + 0.46 * abs(math.cos(petals * th / 2)))
            if r <= rb:
                g[y][x] = "#"
    return g


def sun(size, rays):
    # solid disc + short triangular rays
    return star(size, rays, inner=0.72, sharp=1.0)


def gem(size):
    g = _grid(size)
    c = (size - 1) / 2
    crown = size * 0.36
    for y in range(size):
        for x in range(size):
            dx = abs(x - c)
            if y < crown:
                w = c * (0.32 + (y / crown) * 0.66)
            else:
                p = (y - crown) / (size - crown)
                w = c * (1.0 - p) * 0.98
            if dx <= w:
                g[y][x] = "#"
    return g


# (builder, kwargs) for each milestone 1..20 - growing complexity.
SHAPES = [
    (star, dict(points=5)),
    (gear, dict(teeth=8)),
    (star, dict(points=6)),
    (flower, dict(petals=8)),
    (gem, dict()),
    (star, dict(points=8)),
    (gear, dict(teeth=12)),
    (flower, dict(petals=6)),
    (sun, dict(rays=16)),
    (star, dict(points=10)),
    (gear, dict(teeth=16)),
    (flower, dict(petals=12)),
    (star, dict(points=12)),
    (flower, dict(petals=10)),
    (gem, dict()),
    (star, dict(points=16, inner=0.58)),
    (gear, dict(teeth=20)),
    (flower, dict(petals=16)),
    (sun, dict(rays=24)),
    (star, dict(points=20, inner=0.55)),
]

NAMES = [
    "Vortex", "Cogfall", "Starcrest", "Bloom", "Prism Core",
    "Octastar", "Mechanism", "Hexabloom", "Solar Flare", "Decagram",
    "Great Gear", "Mandala", "Dodecagram", "Bloomcore", "Crown Jewel",
    "Hexadecagram", "Grand Cog", "Petal Storm", "Sunburst", "Infinity Star",
]

# Board size grows 27 -> 65 across the 20 bosses (1000 = biggest).
SIZES = [27 + round(i * 2.0) for i in range(20)]

out_lines = [
    "// GENERATED by tool/generate_bosses.py - do not edit by hand.",
    "// Milestone 'boss' masks for levels 50, 100, ... 1000 (intricate,",
    "// growing in size + complexity so level 1000 is the biggest & hardest).",
    "",
    "const List<String> kBossNames = [",
]
for n in NAMES:
    out_lines.append(f"  '{n}',")
out_lines.append("];")
out_lines.append("")
out_lines.append("const List<List<String>> kBossShapes = [")

for i, ((fn, kw), size) in enumerate(zip(SHAPES, SIZES)):
    g = fn(size, **kw)
    rows = _emit(g)
    cells = sum(r.count("#") for r in rows)
    out_lines.append(f"  // L{(i+1)*50} - {NAMES[i]} ({size}x{size}, {cells} cells)")
    out_lines.append("  [")
    for r in rows:
        out_lines.append(f"    '{r}',")
    out_lines.append("  ],")
out_lines.append("];")
out_lines.append("")

path = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "lib", "data", "boss_shapes.dart"))
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(out_lines))

print("Wrote", path)
for i, ((fn, kw), size) in enumerate(zip(SHAPES, SIZES)):
    g = fn(size, **kw)
    cells = sum(r.count("#") for r in _emit(g))
    print(f"L{(i+1)*50:4d} {NAMES[i]:16s} {size}x{size} cells={cells} "
          f"fill={round(cells/(size*size)*100)}%")
